config/routes.rb
ModelBrandAula::Application.routes.draw do
  resources :rental_requests

  resources :models

  resources :brands

  root 'home#index'

end

app/models/brand.rb
class Brand < ActiveRecord::Base
  has_many :models
end

app/models/model.rb
class Model < ActiveRecord::Base
  belongs_to :brand
  has_many :rental_requests
end

app/models/rental_request.rb
class RentalRequest < ActiveRecord::Base
  belongs_to :model
  has_one :brand, through: :model
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/brands_controller.rb
class BrandsController < ApplicationController
  before_action :set_brand, only: [:show, :edit, :update, :destroy]

  # GET /brands
  # GET /brands.json
  def index
    @brands = Brand.all
  end

  # GET /brands/1
  # GET /brands/1.json
  def show
  end

  # GET /brands/new
  def new
    @brand = Brand.new
  end

  # GET /brands/1/edit
  def edit
  end

  # POST /brands
  # POST /brands.json
  def create
    @brand = Brand.new(brand_params)

    respond_to do |format|
      if @brand.save
        format.html { redirect_to @brand, notice: 'Brand was successfully created.' }
        format.json { render action: 'show', status: :created, location: @brand }
      else
        format.html { render action: 'new' }
        format.json { render json: @brand.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /brands/1
  # PATCH/PUT /brands/1.json
  def update
    respond_to do |format|
      if @brand.update(brand_params)
        format.html { redirect_to @brand, notice: 'Brand was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @brand.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /brands/1
  # DELETE /brands/1.json
  def destroy
    @brand.destroy
    respond_to do |format|
      format.html { redirect_to brands_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_brand
      @brand = Brand.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def brand_params
      params.require(:brand).permit(:name)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @brands = Brand.all
  end
end

app/controllers/models_controller.rb
class ModelsController < ApplicationController
  before_action :set_model, only: [:show, :edit, :update, :destroy]

  # GET /models
  # GET /models.json
  def index
    if params[:brand_id].blank?
      @models = Model.all
    else
      @models = Model.where(brand_id: params[:brand_id])
    end
  end

  # GET /models/1
  # GET /models/1.json
  def show
  end

  # GET /models/new
  def new
    if params.has_key? :brand_id
      @model = Model.new(:brand_id => params[:brand_id])
    else
      @model = Model.new
    end
  end

  # GET /models/1/edit
  def edit
  end

  # POST /models
  # POST /models.json
  def create
    @model = Model.new(model_params)

    respond_to do |format|
      if @model.save
        format.html { redirect_to @model, notice: 'Model was successfully created.' }
        format.json { render action: 'show', status: :created, location: @model }
        format.js {}
      else
        format.html { render action: 'new' }
        format.json { render json: @model.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /models/1
  # PATCH/PUT /models/1.json
  def update
    respond_to do |format|
      if @model.update(model_params)
        format.html { redirect_to @model, notice: 'Model was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @model.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /models/1
  # DELETE /models/1.json
  def destroy
    @model.destroy
    respond_to do |format|
      format.html { redirect_to models_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_model
      @model = Model.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def model_params
      params.require(:model).permit(:name, :brand_id)
    end
end

app/controllers/rental_requests_controller.rb
class RentalRequestsController < ApplicationController
  before_action :set_rental_request, only: [:show, :edit, :update, :destroy]

  # GET /rental_requests
  # GET /rental_requests.json
  def index
    if params[:filter].blank?
      @rental_requests = RentalRequest.all
    else
      @rental_requests = RentalRequest.joins(:model,:brand);
      @rental_requests = @rental_requests.where("rental_requests.name LIKE ? OR models.name LIKE ? OR brands.name LIKE ?", 
                                             "%#{params[:filter]}%",
                                             "%#{params[:filter]}%",
                                             "%#{params[:filter]}%")
    end
  end

  # GET /rental_requests/1
  # GET /rental_requests/1.json
  def show
  end

  # GET /rental_requests/new
  def new
    if params.has_key? :model_id
      @rental_request = RentalRequest.new(:model_id => params[:model_id])
    else
      @rental_request = RentalRequest.new
    end
  end

  # GET /rental_requests/1/edit
  def edit
  end

  # POST /rental_requests
  # POST /rental_requests.json
  def create
    @rental_request = RentalRequest.new(rental_request_params)

    respond_to do |format|
      if @rental_request.save
        format.html { redirect_to @rental_request, notice: 'Rental request was successfully created.' }
        format.json { render action: 'show', status: :created, location: @rental_request }
        format.js { }
      else
        format.html { render action: 'new' }
        format.json { render json: @rental_request.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rental_requests/1
  # PATCH/PUT /rental_requests/1.json
  def update
    respond_to do |format|
      if @rental_request.update(rental_request_params)
        format.html { redirect_to @rental_request, notice: 'Rental request was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @rental_request.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rental_requests/1
  # DELETE /rental_requests/1.json
  def destroy
    @rental_request.destroy
    respond_to do |format|
      format.html { redirect_to rental_requests_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_rental_request
      @rental_request = RentalRequest.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def rental_request_params
      params.require(:rental_request).permit(:name, :phone, :model_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/brands_helper.rb
module BrandsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/models_helper.rb
module ModelsHelper
end

app/helpers/rental_requests_helper.rb
module RentalRequestsHelper
end

app/views/brands/_form.html.erb
<%= form_for(@brand) do |f| %>
  <% if @brand.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@brand.errors.count, "error") %> prohibited this brand from being saved:</h2>

      <ul>
      <% @brand.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/brands/edit.html.erb
<h1>Editing brand</h1>

<%= render 'form' %>

<%= link_to 'Show', @brand %> |
<%= link_to 'Back to list', brands_path %>

app/views/brands/index.html.erb
<h1>Listing brands</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
    </tr>
  </thead>

  <tbody>
    <% @brands.each do |brand| %>
      <tr>
        <td><%= link_to brand.name, brand %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Brand', new_brand_path %>

app/views/brands/new.html.erb
<h1>New brand</h1>

<%= render 'form' %>

<%= link_to 'Back', brands_path %>

app/views/brands/show.html.erb
<p id="notice"><%= notice %></p>

<h1>Car Brand</h1>

<p>
  <strong>Name:</strong>
  <%= @brand.name %>
</p>

<h2>Models</h2>

<ul id="models">
<%= render @brand.models %>
</ul>

<%= form_for(Model.new(:brand_id => @brand.id),
                        remote:true) do |f| %>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>

  <%= f.hidden_field :brand_id %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<p></p>

<%= link_to 'Edit', edit_brand_path(@brand) %> |
<%= link_to 'Destroy', @brand, method: :delete, data: { confirm: 'Are you sure?' } %> |
<%= link_to 'Back to list', brands_path %>

app/views/home/index.html.erb
<h1>Car Rental</h1>


Filter: <input id="filter" type="text">

<ul id="requestlist"></ul>

<%= form_for(RentalRequest.new, remote:true) do |f| %>
<select id="brands" name="rental_request[brand_id]"></select>
<select id="models" name="rental_request[model_id]"></select>

<div class="field" id="name_container">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
</div>
<div class="field" id="phone_container">
    <%= f.label :phone %><br>
    <%= f.text_field :phone %>
</div>
<div class="actions">
    <%= f.submit %>
</div>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ModelBrandAula</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

<%= link_to 'Home', :controller =>'home', :action => :index %>
</body>
</html>

app/views/models/_form.html.erb
<%= form_for(@model) do |f| %>
  <% if @model.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@model.errors.count, "error") %> prohibited this model from being saved:</h2>

      <ul>
      <% @model.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>


  <div class="field">
    <%=  f.select(:brand_id, Brand.all.collect {|b| [b.name, b.id]}, {include_blank: 'Select a brand'}) %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/models/_model.erb
<li><%= link_to model.name, model %> </li>

app/views/models/create.js.erb
$("<%= escape_javascript(render @model) %>").appendTo("#models");

app/views/models/edit.html.erb
<h1>Editing model</h1>

<%= render 'form' %>

<%= link_to 'Show', @model %> |
<%= link_to 'Back to models', models_path %>

app/views/models/index.html.erb
<h1>Listing models</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Brand</th>
    </tr>
  </thead>

  <tbody>
    <% @models.each do |model| %>
      <tr>
        <td><%= link_to model.name, model %></td>
        <td><%= link_to model.brand.name, model.brand %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Model', new_model_path %>

app/views/models/new.html.erb
<h1>New model</h1>

<%= render 'form' %>

<%= link_to 'Back', models_path %>

app/views/models/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <%= link_to @model.brand.name, @model.brand %>
  <%= @model.name %>
</p>

<p><%= link_to 'Submit request', new_rental_request_path(:model_id => @model.id) %> </p>

<%= link_to 'Edit', edit_model_path(@model) %> |
<%= link_to 'Destroy', @model, method: :delete, data: { confirm: 'Are you sure?' } %> |
<%= link_to 'Back to models', models_path %>

app/views/rental_requests/_form.html.erb
<%= form_for(@rental_request) do |f| %>
  <% if @rental_request.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@rental_request.errors.count, "error") %> prohibited this rental_request from being saved:</h2>

      <ul>
      <% @rental_request.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :phone %><br>
    <%= f.text_field :phone %>
  </div>
  <div class="field">
    <%= f.select :model_id, Model.all.collect {|m| [m.brand.name + " " + m.name, m.id]}, {include_blank: 'Select a model'} %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/rental_requests/_rental_request.erb
<li><%= link_to rental_request.name, rental_request %> </li>

app/views/rental_requests/create.js.erb
createLIRequest("<%= escape_javascript(@rental_request.name) %>", "<%= escape_javascript(@rental_request.model.name) %>", "<%= escape_javascript(@rental_request.brand.name) %>");

app/views/rental_requests/edit.html.erb
<h1>Editing rental_request</h1>

<%= render 'form' %>

<%= link_to 'Show', @rental_request %> |
<%= link_to 'Back', rental_requests_path %>

app/views/rental_requests/index.html.erb
<h1>Rental Requests</h1>

<table>
  <thead>
    <tr>
      <th>Number</th>
      <th>Name</th>
      <th>Phone</th>
      <th>Model</th>
    </tr>
  </thead>

  <tbody>
    <% @rental_requests.each do |rental_request| %>
      <tr>
        <td><%= link_to rental_request.id, rental_request %> </td>
        <td><%= rental_request.name %></td>
        <td><%= rental_request.phone %></td>
        <td><%= link_to rental_request.model.name, rental_request.model %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Rental request', new_rental_request_path %>

app/views/rental_requests/new.html.erb
<h1>New Rental Request</h1>

<%= render 'form' %>

<%= link_to 'Back', rental_requests_path %>

app/views/rental_requests/show.html.erb
<p id="notice"><%= notice %></p>

<h1>Rental Request</h1>
<p>
  <strong>Name:</strong>
  <%= @rental_request.name %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @rental_request.phone %>
</p>

<p>
  <strong>Model:</strong>
  <%= link_to @rental_request.model.name, @rental_request.model %>
</p>

<%= link_to 'Edit', edit_rental_request_path(@rental_request) %> |
<%= link_to 'Destroy', @rental_request, method: :delete, data: { confirm: 'Are you sure?' } %> |
<%= link_to 'Back to list', rental_requests_path %>